### ISSUE TITLE
KCV fails to open

### ISSUE THREAD

**Issue by WladimirAndrei** [Yuubari/KanColleViewer#12]
For whatever reason KanColleViewer doesn't open anymore.Used to work like 1 week ago.I also get the same error with Grabacr07's KCV.

```
ERROR, date = 22-Mar-16 18:46:28 PM +02:00, sender = System.Windows.Threading.Dispatcher,
System.Net.Sockets.SocketException (0x80004005): A system call has failed
   at Nekoxy.HttpProxy.Startup(Int32 listeningPort, Boolean useIpV6, Boolean isSetProxyInProcess)
   at Grabacr07.KanColleWrapper.KanColleProxy.Startup(Int32 proxy)
   at Grabacr07.KanColleViewer.Models.ProxyBootstrapper.Try()
   at Grabacr07.KanColleViewer.Application.BootstrapProxy()
   at Grabacr07.KanColleViewer.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Yuubari** [comment]
It's likely something on your side. Have you installed some kind of a firewall or changed Windows network configuration in a weird way? Judging by the error message, the internal proxy is unable to set up a listening port.

Have you tried removing the configuration files/folders as outlined in the FAQ?

**Comment by WladimirAndrei** [comment]
Thanks! Yes, it look like that was the problem.One of the recently installed programs screwed up with the network adapter and/or firewall.
Solved the problem by resetting the network adapter using `netsh`command line.
