### ISSUE TITLE
Error.log

### ISSUE THREAD

**Issue by infinitedestro** [Yuubari/KanColleViewer#19]
Kancolle Viewer was working perfectly fine, but all the sudden when I try to open it now it doesn't open and inside the folder there is an Error.Log text document

**Comment by Yuubari** [comment]
I don't know. Maybe you could _actually_ post the most recent traceback from the error log?

**Comment by LANCER245** [comment]
2016-06-30 11:07 GMT+02:00 Yuubari <notifications@github.com>:

**Comment by infinitedestro** [comment]
This is the latest error post 

ERROR, date = 2016-07-05 10:45:42 PM -07:00, sender = System.Windows.Threading.Dispatcher,
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 6, position 1. (C:\Users\Infinite Destro\AppData\Local\Smooth_and_Flat\KanColleViewer.exe_Url_2vjbg3nny002ptqldf1n1ospzxfrpgah\4.2.4.0\user.config line 6) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 6, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Configuration.XmlUtil.StrictReadToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanFactoriesRecursive(XmlUtil xmlUtil, String parentConfigKey, Hashtable factoryList)
   at System.Configuration.BaseConfigurationRecord.ScanFactoriesRecursive(XmlUtil xmlUtil, String parentConfigKey, Hashtable factoryList)
   at System.Configuration.BaseConfigurationRecord.ScanFactories(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Grabacr07.KanColleViewer.Properties.Settings.get_KcvApiUrl()
   at Grabacr07.KanColleViewer.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Yuubari** [comment]
Have you ever tried checking [the answer here in the FAQ](https://github.com/Yuubari/KanColleViewer/wiki/Frequently-Asked-Questions#my-pc-crashed-and-now-kcv-will-not-start) that I _specifically wrote to prevent these constantly repeated questions?_

Was it _really_ “faster to ask”?
