### ISSUE TITLE
KCV Fails to Open

### ISSUE THREAD

**Issue by Fatso666** [Yuubari/KanColleViewer#8]
Downloaded the Zip file, but trying to open the exe doesn't do anything and it outputs to the error log:

ERROR, date = 2016/02/13 12:53:15 +00:00, sender = System.Windows.Threading.Dispatcher,
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Grabacr07.KanColleViewer.Composition.PluginService.Initialize()
   at Grabacr07.KanColleViewer.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Yuubari** [comment]
Are you sure you do not have any old plug-ins in your plugins folder?

**Comment by Fatso666** [comment]
I unzipped the archive into a new folder so there shouldn't be any old plugins in the folder

**Comment by Yuubari** [comment]
Please check [as described here](https://msdn.microsoft.com/en-us/library/hh925568%28v=vs.110%29.aspx#net_b) which version of the .NET Framework you have installed.

**Comment by Fatso666** [comment]
No idea what version it was, but installing .Net 4.6 fixed the problem.

**Comment by Yuubari** [comment]
Yes, KCV 4.2.x targets .NET 4.6. I'll update the README file a bit later to reflect this.
