### ISSUE TITLE
Fails to open

### ISSUE THREAD

**Issue by SirDekar** [Yuubari/KanColleViewer#9]
Downloaded fresh .zip
Using .Net 4.6

Error message is as follows:
# 

ERROR, date = 1/03/2016 11:45:12 AM +11:00, sender = System.Windows.Threading.Dispatcher,
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderShipTranslationSet.Read5_ShipTranslationSet()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Grabacr07.KanColleWrapper.TranslationDataProvider.LoadXml(TranslationProviderType type, String culture)
   at Grabacr07.KanColleWrapper.TranslationDataProvider.LoadLocalTranslations(String culture)
   at Grabacr07.KanColleWrapper.TranslationDataProvider.ChangeCulture(String culture, Boolean firstRun)
   at Grabacr07.KanColleWrapper.KanColleClient.DeferredInit(Object sender, IKanColleClientSettings value)
   at Grabacr07.KanColleWrapper.KanColleClient.set_Settings(IKanColleClientSettings value)
   at Grabacr07.KanColleViewer.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Yuubari** [comment]
You could try following the FAQ and deleting %AppData%\Smooth and Flat\KanColleViewer! (or just the Translations folder there).

**Comment by SirDekar** [comment]
Cheers Yuubari. I must have skipped over that part in the FAQ, sorry for wasting your time :)

**Comment by Yuubari** [comment]
To be quite honest this is an extremely weird occurrence, as these files are only touched by KCV itself. You might have had an unexpected system shutdown or something along these lines.

I'll consider handling these exceptions in the upcoming releases.
